# Generated by Django 5.2.7 on 2025-10-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
    ]
